### ISSUE TITLE
Setting up package environment

### ISSUE THREAD

**Issue by gboduljak** [TristanBilot/mlx-graphs#1]
I know this is a first step, but I think we should start properly. I think it is a great idea to use ``Poetry`` or similar package manager for ensuring reproducible dependencies. I am not an expert on Python library development, but I feel that it is necessary to start with a reproducible environment. Let me know what you think.

**Comment by TristanBilot** [comment]
Totally agree that we should start properly. 
I didn't have a first good experience with poetry on a large project, but I'm willing to give it another chance!
Are you familiar with it?

**Comment by gboduljak** [comment]
> Totally agree that we should start properly. I didn't have a first good experience with poetry on a large project, but I'm willing to give it another chance! Are you familiar with it?

I am not too familiar with it and it worked well for my relatively simple use-cases. I think we should ask authors of MLX for an advice how to:
1.  Set up Python package development environment
2.  Set up CI/CD for tests and deployment

**Comment by TristanBilot** [comment]
Very good idea!

**Comment by TristanBilot** [comment]
Using git-flow with `features/*` branches would be good to separate our developments, what do you think?

**Comment by gboduljak** [comment]
> Using git-flow with `features/*` branches would be good to separate our developments, what do you think?

Seems great.

**Comment by TristanBilot** [comment]
Setting up the installation of the `mlx-graphs` package locally with `pip install -e .` has to be done before diving into writing any tests and implementations. Do you consider working on that @gboduljak ?

**Comment by gboduljak** [comment]
> Setting up the installation of the `mlx-graphs` package locally with `pip install -e .` has to be done before diving into writing any tests and implementations. Do you consider working on that @gboduljak ?

I cannot work on that until Friday :(

**Comment by TristanBilot** [comment]
Ok! No prob :)

**Comment by francescofarina** [comment]
I'm happy to start setting that up and can allocate some time today.

**Comment by francescofarina** [comment]
Packaging with poetry set up in https://github.com/TristanBilot/mlx-graphs/pull/9

**Comment by francescofarina** [comment]
NB, building and publishing on pypy is straightforward with poetry but let's first set up CI/CD and add some juice to the package.

**Comment by francescofarina** [comment]
Setup for local dev should be ok as of ad915d2409e585abd7f7153c0476bb378c278582. Shall we close this? And maybe open a new one later on to setup some CI and the actual publishing on Pypy?

**Comment by francescofarina** [comment]
Added initial CI in https://github.com/TristanBilot/mlx-graphs/pull/22

**Comment by TristanBilot** [comment]
Are we done here?

**Comment by francescofarina** [comment]
Probably yes, we just need to setup how we release the package. Ideally we'd setup a [Github action](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) for that but since we'll need to build it on Apple Silicon we'll likely have to do it manually for the moment.

**Comment by TristanBilot** [comment]
Ok, yes it seems logical for the moment to build releases locally. For the Pypi repo, idk if we have to do it or we wait once we add mlx-graphs to ml-explore organization?

**Comment by francescofarina** [comment]
I think it's usually better to release it on Pypi so that it can be easily installed.

**Comment by francescofarina** [comment]
Closing this and moving the package release and documentation publication to a new one.
