### ISSUE TITLE
Make default merge behavior to squash and merge

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#12]
Right now we're using regular “merge” commits which include all of the git commits in the history of the target branch. Squashing flattens them to one commit.

**Comment by TristanBilot** [comment]
Never used that before but it's a cool idea, is it as simple as doing `git merge --squash feature_branch`?

**Comment by francescofarina** [comment]
From CLI yes - on GitHub it needs to be forced via `Settings` -> `General` -> 
<img width="795" alt="Screenshot 2024-01-14 at 17 10 28" src="https://github.com/TristanBilot/mlx-graphs/assets/19568231/8c03a1c7-c935-4cf2-a911-8d6a03d80baa">

**Comment by francescofarina** [comment]
@TristanBilot looks like you need to do it as the owner of the repo.

**Comment by TristanBilot** [comment]
Done!
