### ISSUE TITLE
Adopt common convention on names and shapes

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#17]
Let's decide which convention to adopt for naming attributes, their shapes and the order in which they're passed to functions.

Below is what I propose but let's iterate on that

| Attribute | name | shape | order |
|----------|-------|-------|------|
| Edge index | `edge_index` | `[2, # edges]` | 1 |
| Node features | `node_features` | `[# nodes, node_feature_dim]`| 2 |
| Edge features | `edge_features` | `[# edges, edge_feature_dim]`| 3 |
| Graph (global) features | `graph_features` | `[graph_feature_dim]`| 4 |

**Comment by TristanBilot** [comment]
Sorry for the late reply!
I'm ok with this convention.

**Comment by francescofarina** [comment]
Cool, I'll work on a PR to make things uniform across the repo.
