### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#32]
This requires setting up a Github Pages website (or one on readthedocs), building the docs via `cd docs && make html` and pushing `docs/html`. Can also be automated via a [GitHub action](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by francescofarina** [comment]
@TristanBilot you may have to do this as you're the repo owner but I'm happy to help.

**Comment by TristanBilot** [comment]
Ok I'll work on that.
