### ISSUE TITLE
Release package on PyPI

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#33]
Ideally we'd set up a CI/CD workflow (as [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)). However, we'll likely have to do it manually as the build step may need to be done on Apple Silicon.

**Comment by francescofarina** [comment]
We can also set up a workflow on circleci as Apple Silicon runners are available there.

**Comment by TristanBilot** [comment]
Not sure it's worth to have a full CI/CD dedicated to the releases yet, we can start with a simple local build?

**Comment by francescofarina** [comment]
When you say local build you mean building locally and then manually pushing to PyPI?

**Comment by TristanBilot** [comment]
Yes

**Comment by francescofarina** [comment]
Yes, I think that's fine for now. 

No rush to implement a CICD pipeline. It's pretty straightforward to do it when we need it.
