### ISSUE TITLE
Implement remove_self_loops() and add_self_loops()

### ISSUE THREAD

**Issue by TristanBilot** [TristanBilot/mlx-graphs#38]
These operations are frequently used.
[PyG code](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/loop.html#remove_self_loops).

**Comment by Kheims** [comment]
I can handle this !

**Comment by Kheims** [comment]
Pyg's add_self_loops add self loops wether they are present in the initial edge_index or not 
```
edge_index = torch.tensor([[0, 1, 0],
        ...                            [1, 0, 0]])
add_self_loops(edge_index)
        (tensor([[0, 1, 0, 0, 1],
                [1, 0, 0, 0, 1]]),
```
 whereas add_remaining_self_loops only does so for the non present self loops, in which case would we prefer the first over the second, if it is needed wouldn't it be preferable to have it as an argument to a single function ?

**Comment by TristanBilot** [comment]
> whereas add_remaining_self_loops only does so for the non present self loops, in which case would we prefer the first over the second, if it is needed wouldn't it be preferable to have it as an argument to a single function ?

I agree, using a single function would be sufficient here. However, we have to think about the case of edge-attributed graphs, where adding self-loops is not only adding self edges to the edge_index, but also add edge feature vectors of the same shape as the actual edge features. How PyG handles that? I think the user should have the possibility to provide its own edge features, but how would he know the number of edge features that don't have self-edges yet in the edge index?

Anyway, once we know how to handle this case, we can think whether it's more intuitive to use a single function with default behavior to add remaining loops, or add two functions.

**Comment by TristanBilot** [comment]
Also, we have to think how we handle adding and removing self loops directly on a batch. I think it should work as is on the batch, as graphs in the batch are not connected, but we have to remind to write tests for this case once we have merged both branches (and modify the signature of `add/remove_self_loops`'s `edge_index` to specify the function accepts an `Union[GraphData, Batch]`).

**Comment by francescofarina** [comment]
@Kheims I started implementing this at https://github.com/TristanBilot/mlx-graphs/pull/45/files - feel free to contribute. To address the point above on possibly repeated self loops I added an arg to control that

**Comment by Kheims** [comment]
Great ! Will take a look this night
