### ISSUE TITLE
Implement some datasets

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#43]

**Comment by TristanBilot** [comment]
In DGL, they have stored all datasets on their server and download them using direct access via URL such as `https://data.dgl.ai/dataset/yelp.zip` ([see](https://github.com/dmlc/dgl/blob/0a42d863b740e3e13d79ee081d3792a4a04aed87/python/dgl/data/utils.py#L54C5-L54C17))

**Comment by TristanBilot** [comment]
We'll have to think how we can store them, or by simply using the URLs from DGL? I don't know if it's totally free of use.

**Comment by francescofarina** [comment]
It seems freely accessible so we can start there to experiment and eventually directly store our custom versions somewhere.
