### ISSUE TITLE
GraphData __repr__

### ISSUE THREAD

**Issue by TristanBilot** [TristanBilot/mlx-graphs#48]
I wonder which representation of `GraphData` should we use?
When we `print(data)`, we have this:
```python
GraphData(edge_index=array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=float32), node_features=array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=float32))
```

PyG has this:
```python
Data(edge_index=[2, 10], node_features=[5, 5])
```

What do you think of this?
```python
GraphData(
	edge_index(shape=[2, 10])
	node_features(shape=[5, 5]))
```
or 
```python
GraphData(
        edge_index=[2, 5], int32
        node_features=[5], int32)
```

**Comment by francescofarina** [comment]
I'm personally not a big fun of the PyG way as I find it a bit confusing. I think need to either show the content of the args or, if we just show the shapes, make it clear that it's the shapes we're showing. 

This one you propose could be good
```python
GraphData(
	edge_index(shape=[2, 10])
	node_features(shape=[5, 5]))
```
but I think the last one is not optimal.

Another option could be to have
```python
GraphData(num_edges=10, num_nodes=5, num_node_features=5)
```

**Comment by TristanBilot** [comment]
Ok I agree with the shape. However, just printing the length does not provide enough information on the overall graph, and the shape already indicates the number of nodes and edges so I think we should keep the shapes.

**Comment by francescofarina** [comment]
Cool, let's go with that then.

**Comment by TristanBilot** [comment]
So are we removing the dtype from the print too?

**Comment by francescofarina** [comment]
Yeah, I think that's nice with the dtype
