### ISSUE TITLE
Upgrade mlx to 0.1

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#66]
mlx 0.1 introduces some breaking changes that we need to handle

**Comment by TristanBilot** [comment]
Which breaking changes?

**Comment by francescofarina** [comment]
I haven't explored it in depth yet but upgrading mlx to 0.1 and running our tests I can see that array shapes are now tuples instead of arrays (see [here](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.array.shape.html?highlight=shape#mlx.core.array.shape) which breaks a few things on our end.
