### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by francescofarina** [TristanBilot/mlx-graphs#7]
Let's decide on which license to use. I guess MIT is fine.

**Comment by TristanBilot** [comment]
yep I suggest we follow the [same as in PyG](https://github.com/pyg-team/pytorch_geometric/blob/5c561949d67123cf6ea892812e2357ce9bd9a819/LICENSE) and in MLX, which is to use MIT.

**Comment by francescofarina** [comment]
Cool, I'll add it in the PR with the initial packaging.

**Comment by francescofarina** [comment]
LICENSE added in https://github.com/TristanBilot/mlx-graphs/pull/9
